title: Zehao Gu's Homepage
page-top-title: Zehao Gu
top-section-bg-text: Computer Science
home-subtitle: Garrett&ensp;|&ensp;Zehaogu&ensp;|&ensp;顾泽皓
copyright-text: '&copy; Zehao Gu 2024-2025. All Rights Reserved.'
