title: Zehao Gu's Homepage
page-top-title: Zehao Gu
hero-name: Zehao Gu
hero-title: Ads Algorithm Engineer @ Bytedance Tiktok
home-subtitle: Garrett&ensp;|&ensp;Zehaogu&ensp;|&ensp;顾泽皓
copyright-text: '&copy; Zehao Gu 2024-2026. All Rights Reserved.'